name: bhgmall

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'
  watch:
    types: started
  repository_dispatch:
    types: bhgmall
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: sunshunli/my_scripts
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【华联万柳签到脚本】'
        run: |
          node --version